import type { Metadata } from 'next'
import { Space_Mono, Saira } from 'next/font/google'
import './globals.css'

const saira = Saira({
    subsets: ["latin"],
    variable: "--font-saira",
});
const spaceMono = Space_Mono({
  subsets: ["latin"], variable: "--font-spaceMono",
  weight: ['400','700']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${saira.variable} ${spaceMono.variable}`}>{children}</body>
    </html>
  )
}
